---
name: ((minio_deployment_name))

releases:
- name: minio
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

variables:
- name: minio_accesskey
  type: password
- name: minio_secretkey
  type: password

instance_groups:
- name: minio
  azs: [CONTROL-PUBLIC]
  instances: 1
  jobs:
  - name: minio-server
    release: minio
    templates:
    - name: minio-server
    provides:
      minio-server: {as: minio-link}
    properties:
      credential:
        accesskey: ((minio_accesskey))
        secretkey: ((minio_secretkey))
      port: 9000
  networks:
  - name: control-public
  vm_type: micro
  persistent_disk_type: 1048576
  stemcell: default

- name: tests
  azs: [CONTROL-PUBLIC]
  instances: 1
  lifecycle: errand
  post_deploy: true
  jobs:
  - name: smoke-tests
    release: minio
    templates:
    - name: smoke-tests
    consumes:
      minio: {from: minio-link}
  networks:
  - name: control-public
  vm_type: micro
  persistent_disk_type: 2048
  stemcell: default

- name: bucket-seeding # To create default buckets after manifest-deploy
  azs: [CONTROL-PUBLIC]
  instances: 1
  lifecycle: errand
  post_deploy: true
  jobs:
  - name: mc
    release: minio
    templates:
    - name: mc
    consumes:
      minio: {from: minio-link}
    properties:
      script: |
        #!/bin/sh
        mc mb kirklab/kirklab-buildpacks-bucket
        mc mb kirklab/kirklab-droplets-bucket
        mc mb kirklab/kirklab-packages-bucket
        mc mb kirklab/kirklab-resources-bucket
        mc mb kirklab/kirklab-pivnet-products
        mc mb kirklab/kirklab-platform-automation
        mc mb kirklab/kirklab-platform-automation-assign-stemcell-config
        mc mb kirklab/kirklab-platform-automation-control-installation
        mc mb kirklab/kirklab-platform-automation-installation
        mc mb kirklab/kirklab-mysql-backups
  networks:
  - name: control-public
  vm_type: micro
  persistent_disk_type: 2048
  stemcell: default

update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 1

